#+TITLE: Config Org
#+OPTIONS: toc:2 num:nil ^:nil

** Basic Setup
Set an empty list for my Org Capture Templates.
#+BEGIN_SRC emacs-lisp
(setq org-capture-templates '())
#+END_SRC

** Keybindings
Bind a few handy keys.
#+BEGIN_SRC emacs-lisp
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\C-ca" 'org-agenda)
(define-key global-map "\C-cc" 'org-capture)
#+END_SRC

** GTD Setup
The GTD part of this config is heavily inspired by [[https://emacs.cafe/emacs/orgmode/gtd/2017/06/30/orgmode-gtd.html][Org-mode GTD]].

Setup agenda files with /index/, /gtd/ and /tickler/.
#+BEGIN_SRC emacs-lisp
(setq org-agenda-files '("~/gtd/inbox.org"
                         "~/gtd/gtd.org"
                         "~/gtd/tickler.org"))
#+END_SRC

Refile targets are /gtd/, /someday/ and /tickler/.
#+BEGIN_SRC emacs-lisp
(setq org-refile-targets '(("~/gtd/gtd.org" :maxlevel . 3)
                           ("~/gtd/someday.org" :level . 1)
                           ("~/gtd/tickler.org" :maxlevel . 2)))
#+END_SRC

The most basic logging is to keep track of /when/ a certain TODO item was finished.
#+BEGIN_SRC emacs-lisp
(setq org-log-done 'time)
#+END_SRC

Setup capture templates.
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-capture-templates '("t" "Todo [inbox]" entry
                                      (file+headline "~/gtd/inbox.org" "Tasks")
                                      "* TODO %i%?"))
(add-to-list 'org-capture-templates '("T" "Tickler" entry
                                      (file+headline "~/gtd/tickler.org" "Tickler")
                                      "* TODO %i%? \n %T"))
#+END_SRC

Customize the sequence of TODOs statuses.
#+BEGIN_SRC emacs-lisp
(setq org-todo-keywords '((sequence "TODO(t)" "WAITING(w)" "|"
                                    "DONE(d)" "CANCELLED(c)")))
#+END_SRC

** Grocery List
This is my grocery list template. I like to add a TODO item with with the current /inactive/ timestamp and a series of checkbox.
I store my list in a Dropbox folder and use it on the go via Orgzly.
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-capture-templates '("g" "Grocery" entry
                                      (file+headline "~/Dropbox/org/grocery.org" "Grocery")
                                      "* TODO Spesa del %u [/]\n- [ ] %?"))
#+END_SRC

** Exporters From Contrib
**** Confluence
Require =ox-confluence= to export framework, since I like to write my Confluence wiki pages outside of Confluence itself.
#+BEGIN_SRC emacs-lisp
(require 'ox-confluence)
#+END_SRC
